### ISSUE TITLE
QR codes not scanning

### ISSUE THREAD

**Issue by Crelam** [jamie-mh/AuthenticatorPro#286]
**Describe the bug**

I seem to be unable to successfully scan a barcode importing from Google Authenticator.  To my eye, it looks like the scanning dialog that opens the camera is 'squished' on the horizontal plane, distorting the QR Code.  I have replicated this issue across two devices.

**App Version**
Version number of the app, found in Settings -> About.

1.15.0

**Additional context**

**Comment by jamie-mh** [comment]
Hi,

Can you be more specific. Does the code scan then fail to import or does it simply not leave the scanning screen? Does it work when scanning from an image?

Thanks

**Comment by Crelam** [comment]
It does not leave the scanning screen.  I tried taking a picture and it would not import, stating that there was no valid QR code.  This issue may be exasperated due to the camera on my tablet (Fire HD 10) is kinda crap.  I was able to work around this by using a different barcode reader (Binary Eye) on my tablet to read the barcode, and import using the string.

And just to be clear, I tried to scan the Google Authenticator bar code within the Authenticator Pro app from both my tablet and phone.  Both had the 'squished' effect and would not read the code.

**Comment by jamie-mh** [comment]
I think the squished camera is a red herring. It's just a 16:9 camera feed being stretched to fit a taller display, the actually processing happens on the correctly sized image.

The issue is most likely due to the QR code being too dense. The more information, the harder it is to read.
I will clarify the workaround in the import guide on the wiki.

**Comment by Crelam** [comment]
Its certainly possible that the squished effect is simply a UX aberration.  However the fact that I was able to successfully scan the 8 account code using another app (Binary Eye) on the same device implies there is something wrong.  If its not the "squished image" then its something behind the scenes.

But given that its easy enough to work around, I can understand this bug being a low priority.  This app is an Authenticator first and the QR scan is just a means to that end, while Binary Eye's primary function is barcode scanning.

**Comment by infinity85** [comment]
I have the same or a very similar issue too: 

my main cam on a galaxy s21 plus shows a picture on the display with a totally wrong aspect ratio while scanning with authenticator pro. And this wrong aspect ratio is only displayed if trying to scan in authenticator pro. Haven't seen such an issue on my device anywhere else.

**Comment by jamie-mh** [comment]
This is an issue in the QR code library used by the app: https://github.com/Redth/ZXing.Net.Mobile/issues/808
I've made a few changes in 9cdb256 to hopefully reduce the stretching of the display.

**Comment by PremiumSaltine** [comment]
My display is not stretched at all. It isn't just the big QR code from Google Authenticator either. My Pixel 6 camera shows every QR code very clearly. The app just doesn't do anything them all with it.

**Comment by PremiumSaltine** [comment]
An update on my issue. I decided to try installing older versions. 1.15.5 would not scan QR codes. 1.15.4 would not install. It said there was a parsing issue. 1.15.3 has a squished camera view, but scans QR codes just fine.

**Comment by jamie-mh** [comment]
Yes, in 1.15.4 I made some changes to prevent the camera view from being squished. It seems it has fixed the distortion but has made it less reliable at reading QR codes for some users. Perhaps the resolution is now too large and QR code recognition is not fast enough. I will investigate further.

**Comment by jamie-mh** [comment]
Hi everyone,

Here is a dev version of the app with some changes to the QR code scanning. If anyone experiencing this issue can test this and give me your feedback that would be appreciated. I'm not able to reproduce the issue in any app version with my device (S10+).

It has a different package name so it won't overwrite an existing install.

Thanks

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7788535/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by PremiumSaltine** [comment]
Tried the DEV Build. Screen isn't as squished as 1.15.3. It scanned a QR code once, then said "An Error Occurred." After that, I couldn't get it to scan another QR code.

**Comment by jamie-mh** [comment]
Ok. I've reverted it back to the way it worked in 1.15.3. The screen will appear squished but at least it mostly works. I might come back to this later if I find a better solution.

**Comment by mxbndr** [comment]
I am also having this issue now. When the scanner opens, the image is squished/stretched and does not scan. Viewing the same QR code through the camera app and Google Lens recognizes just fine (but doesn't accomplish the goal of importing, obviously).

Pixel 4a

**Comment by MagicLike** [comment]
Any updates to this? (I am also have the issue and end up scanning the QR code through rotating my device)

**Comment by jamie-mh** [comment]
In 1.17.0, the ZXing barcode scanner has been replaced with MLKit. It appears to be faster and more reliable. Furthermore, the preview is no longer stretched.

**Comment by daylightdev** [comment]
Hi.  The QR code scanning has stopped working in the latest version (1.17.0).
_Redmi Note 8, Android 13 (Arrow OS, Custom ROM)_

_But I can download the image or use the provided key._ Thank you for the excellent project.

**Comment by technodrome** [comment]
+1 , v 1.17.3 F-Droid
QR import does not do anything for me. Regardless of black or white background, QR just sits in the middle of the frame and the app does nothing with it. No error message. Would be nice for UX to show some feedback if reading is not working properly or insert a button to trigger a manual scan.

**Comment by Heus-Sueh** [comment]
> +1 , v 1.17.3 F-Droid
> When scanning a QR code using camera, it does not do anything for me. Regardless of black or white QR background, the code just sits in the middle of the camera frame and the app does nothing with it. No error message. Would be nice for UX to show some feedback if reading is not working properly or insert a button to trigger a manual scan. 

+1 I can confirm that the same thing happens to me

**Comment by jamie-mh** [comment]
There is no error message because the scanner doesn't know if there is a QR code or not, it just can't find anything. A manual scan button would make a difference.
The F-Droid releases use XZing for scanning whereas the Google Play releases use MLKit. I would recommend using the latter as it's more reliable.

**Comment by technodrome** [comment]
If you use different libraries for different release channels, this should be clearly documented. I haven't found any mention of this in the readme.

**Comment by Heus-Sueh** [comment]
> If you use different libraries for different release channels, this should be clearly documented. I haven't found any mention of this in the readme.

I agree with that

**Comment by cewbdex** [comment]
This app is great, however QR scanning did not work for me for a single time. I have to scan via Binary Eye app, then save to gallery and then load. Could you use the same library as they do or launch their app to scan?

**Comment by Heus-Sueh** [comment]
I have a proposal to solve this problem: two versions in IzzyOnDroid one that includes free software (XZing) that would be called Authenticator Pro Libre and the normal version that would include the MLKit library and keep the name Authenticator Pro. 

@jamie-mh  please have a look this proposal

**Comment by jamie-mh** [comment]
Please keep this thread on topic. There is already a distinction in the about screen and the names of the APKs.
Naturally, the expectation when you download an F-Droid style release is that it's 100% free software.

**The Google Play releases include:**
- Wear OS support (depends on the non-free Google Play Services)
- MLKit Barcode scanning (includes a proprietary ML model)

I'm going to make some tweaks to the ZXing scanning in the next release. However, it's been working fine for me every time on every device I test.

As stated above:
> The F-Droid releases use XZing for scanning whereas the Google Play releases use MLKit. I would recommend using the latter as it's more reliable.

**Comment by Heus-Sueh** [comment]
> Please keep this thread on topic. There is already a distinction in the about screen and the names of the APKs. Naturally, the expectation when you download an F-Droid style release is that it's 100% free software.

I understand, it ends up being frustrating the app doesn't work as it should

> I'm going to make some tweaks to the ZXing scanning in the next release. However, it's been working fine for me every time on every device I test.

this bug is something very strange, you say that the f-droid version works normally on all the devices you tested, but here on my device I tried several times to scan the QRCode but the app didn't give any feedback, but I tested the play store version and it worked the first time :thinking:, anyway I hope these tweaks on XZing solve the problem. :+1: 

Is there any way I can help? with logs, device specifications...

**Comment by cewbdex** [comment]
@jamie-mh, could you use https://github.com/zxing-cpp/zxing-cpp ? it works great.

**Comment by jamie-mh** [comment]
@cewbdex  I would rather avoid native code if at all possible, it makes the build more complicated as it must be compiled into a shared library and needs a wrapper.

I've made a beta release with some changes to the QR code scanning. I've tested this on an old phone with a bad camera, and it works fine for me. If anyone can run some tests on their devices, feedback is appreciated.

[https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.19.0-beta](https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.19.0-beta)

Thanks

**Comment by Heus-Sueh** [comment]
> I've made a beta release with some changes to the QR code scanning. I've tested this on an old phone with a bad camera, and it works fine for me. If anyone can run some tests on their devices, feedback is appreciated.

I tried the beta but unfortunately the same thing, try to scan the qrcode but it doesn't give any feedback

here is some information about my camera that might help:
![Screenshot_20230430-125208_Device Info HW~01](https://user-images.githubusercontent.com/98482469/235363325-764c7461-7b36-415e-9186-e567b5a22d5f.png)

**Comment by jamie-mh** [comment]
Hi,

I can't see anything in the camera info that would be a problem. Can you tell me more about the QR code you are scanning:
- Is it in focus or blurry in the viewfinder?
- Is the code black on white with a solid white border around it?
- Can it be read easily by QR code scanning apps (Binary Eye for instance)?

Thanks

Btw, this is the code I'm testing with.

![standard-totp](https://user-images.githubusercontent.com/7887162/235424405-4796dc91-8ee1-4e13-9c8f-5c698507cbef.png)

**Comment by cewbdex** [comment]
![Screenshot_2023-05-01-15-24-30-290_me jmh authenticatorpro beta](https://user-images.githubusercontent.com/9021297/235457685-d4ae222c-0dc0-45e5-bddf-89a27ab9e1da.jpg)


Used the beta you sent, first file, nothing at all.

**Comment by Heus-Sueh** [comment]
> * Is it in focus or blurry in the viewfinder?
>* Is the code black on white with a solid white border around it?

it doesn't seem to be out of focus, it can focus normally

![Screenshot_20230501-150216_Authenticator Pro](https://user-images.githubusercontent.com/98482469/235502574-fbd9c52d-33c2-45de-8cf3-7976bdc88000.png)

>* Can it be read easily by QR code scanning apps (Binary Eye for instance)?

qrcode works with binary eye normally

i was testing the qrcode on a generic website, but I tested this qrcode you sent but it didn't work either

**Comment by jamie-mh** [comment]
Thanks for the feedback.

I was able to find a device where the scanning did not work. I believe this issue is due to the requested resolution (1280x720) not being used, but rather the full resolution of the camera. Since the resolution is too large, the processing was too slow.

I've updated the APKs on the release with the changes. It appears to work fine now.

**Comment by cewbdex** [comment]
I can confirm it works on my device now, thank you.

**Comment by Heus-Sueh** [comment]
I can confirm it works on my device too :tada:

**Comment by jamie-mh** [comment]
Thanks for helping me test this. The fix will be included in the next release.

**Comment by Heus-Sueh** [comment]
we can close this issue as the bug is resolved

**Comment by gabeweb** [comment]
Hi,

I downloaded Stratum from Play Store (1.0.2) and QR codes scanning still not working since the last version of Authenticator Pro.

Android 14.0 / HyperOS 1.0.10 (Redmi Note 13 4G).

On other authenticator apps (Bitwarden Authenticator) the QR code scanning is very quickly.
