### ISSUE TITLE
Backups fail when select encrypted and not entering a password.

### ISSUE THREAD

**Issue by Krojack** [jamie-mh/AuthenticatorPro#766]
**Describe the bug**
Can no longer create backup with no password.

**To Reproduce**
1. Go to backup
2. Select "Backup to encrypted file"
3. Don't enter a password.
4. Get warning message like before and continue.
5. Message popups up saying "an error has occurred"
6. See a backup file created but it's zero bytes in size.

**Expected behavior**
A backup file created with data, not an empty file.

**App Version**
1.19.0

**Additional context**
This happens with auto backup with no password set as well.
This worked with previous versions. Maybe some update with the better encryption changes?
Also I understand the risk not using a password. For now I set a password for auto backups.

**Comment by jamie-mh** [comment]
Hi @Krojack ,

Thanks for the report. Yep, this is an oversight on my part. Fixed in 7ae6d58.

Cheers

**Comment by laduchesneau** [comment]
Hi, 

I'm still experiencing this bug, with the same description and same step to reproduce. The only exception is that there is no error displayed when saving.  The file saved is still empty.

App version 125.1

Let me know if you prefer I open a new bug report.
